// // app/page.tsx or similar
// import { Metadata } from 'next';

//   const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default metadata

// // Other code for the page component


import { Metadata } from 'next';

// Define your metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Create the page component
const Page = () => {
  return (
    <div>
      <h1>Your Page Content</h1>
      <p>This is where your page main content goes.</p>
    </div>
  );
};

// Export the page component as default
export default Page;
